business_name: Fulcrum Suspensions
business_url: https://fulcrumsuspensions.com.au
business_location: Australia
business_aliases:
  - Fulcrum
  - Fulcrum Suspension
num_consumer_queries: 5
num_business_queries: 5
